#!/usr/bin/env bash
# Install Nginx with the following configurations:

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World' > /var/www/html/index.html
service nginx start
