#!/usr/bin/env bash
#loops from 1 to 10

num=0
while ((num < 10));
do
	((num++));

	if ((num == 4));
	then
		echo "bad luck";
	elif ((num == 8));
	then
	  	echo "good luck";
	else
		echo "Best School";
	fi
done

