#!/usr/bin/env bash
# configure a ufw to block all firewall to  block all incoming traffic
# except TCP ports 22, 443 and 80


sudo pacman -Syu
sudo pacman -S ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo systemctl stop ufw
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
